// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: streaming/v1/streaming.proto

package streamingv1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListStreamsRequest requests a list of accessible streams
type ListStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsRequest) Reset() {
	*x = ListStreamsRequest{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsRequest) ProtoMessage() {}

func (x *ListStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamsRequest) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{0}
}

// ListStreamsResponse contains the list of streams
type ListStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamInfo          `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsResponse) Reset() {
	*x = ListStreamsResponse{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsResponse) ProtoMessage() {}

func (x *ListStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamsResponse) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *ListStreamsResponse) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

// StreamInfo contains metadata about a stream (matches models.Stream)
type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RetentionDays int32                  `protobuf:"varint,6,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	Topic         string                 `protobuf:"bytes,7,opt,name=topic,proto3" json:"topic,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *StreamInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StreamInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StreamInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StreamInfo) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *StreamInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StreamInfo) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StreamInfo) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *StreamInfo) GetDeletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// OpenStreamRequest requests to open a stream
type OpenStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // TODO: Add start_mode/offset support when implemented in backend
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStreamRequest) Reset() {
	*x = OpenStreamRequest{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStreamRequest) ProtoMessage() {}

func (x *OpenStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStreamRequest.ProtoReflect.Descriptor instead.
func (*OpenStreamRequest) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *OpenStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// StreamMessage represents a message streamed to CLI clients (matches messages.StreamMessage)
type StreamMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Query         map[string]string      `protobuf:"bytes,5,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampNs   int64                  `protobuf:"varint,6,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_streaming_v1_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_streaming_v1_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *StreamMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StreamMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StreamMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *StreamMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *StreamMessage) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *StreamMessage) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *StreamMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_streaming_v1_streaming_proto protoreflect.FileDescriptor

const file_streaming_v1_streaming_proto_rawDesc = "" +
	"\n" +
	"\x1cstreaming/v1/streaming.proto\x12\x11frkr.streaming.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12ListStreamsRequest\"N\n" +
	"\x13ListStreamsResponse\x127\n" +
	"\astreams\x18\x01 \x03(\v2\x1d.frkr.streaming.v1.StreamInfoR\astreams\"\xf5\x02\n" +
	"\n" +
	"StreamInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0eretention_days\x18\x06 \x01(\x05R\rretentionDays\x12\x14\n" +
	"\x05topic\x18\a \x01(\tR\x05topic\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"0\n" +
	"\x11OpenStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\x93\x03\n" +
	"\rStreamMessage\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12G\n" +
	"\aheaders\x18\x03 \x03(\v2-.frkr.streaming.v1.StreamMessage.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12A\n" +
	"\x05query\x18\x05 \x03(\v2+.frkr.streaming.v1.StreamMessage.QueryEntryR\x05query\x12!\n" +
	"\ftimestamp_ns\x18\x06 \x01(\x03R\vtimestampNs\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc8\x01\n" +
	"\x10StreamingService\x12\\\n" +
	"\vListStreams\x12%.frkr.streaming.v1.ListStreamsRequest\x1a&.frkr.streaming.v1.ListStreamsResponse\x12V\n" +
	"\n" +
	"OpenStream\x12$.frkr.streaming.v1.OpenStreamRequest\x1a .frkr.streaming.v1.StreamMessage0\x01B;Z9github.com/frkr-io/frkr-proto/go/streaming/v1;streamingv1b\x06proto3"

var (
	file_streaming_v1_streaming_proto_rawDescOnce sync.Once
	file_streaming_v1_streaming_proto_rawDescData []byte
)

func file_streaming_v1_streaming_proto_rawDescGZIP() []byte {
	file_streaming_v1_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_v1_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_v1_streaming_proto_rawDesc), len(file_streaming_v1_streaming_proto_rawDesc)))
	})
	return file_streaming_v1_streaming_proto_rawDescData
}

var file_streaming_v1_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_streaming_v1_streaming_proto_goTypes = []any{
	(*ListStreamsRequest)(nil),  // 0: frkr.streaming.v1.ListStreamsRequest
	(*ListStreamsResponse)(nil), // 1: frkr.streaming.v1.ListStreamsResponse
	(*StreamInfo)(nil),          // 2: frkr.streaming.v1.StreamInfo
	(*OpenStreamRequest)(nil),   // 3: frkr.streaming.v1.OpenStreamRequest
	(*StreamMessage)(nil),       // 4: frkr.streaming.v1.StreamMessage
	nil,                         // 5: frkr.streaming.v1.StreamMessage.HeadersEntry
	nil,                         // 6: frkr.streaming.v1.StreamMessage.QueryEntry
	(*timestamp.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_streaming_v1_streaming_proto_depIdxs = []int32{
	2, // 0: frkr.streaming.v1.ListStreamsResponse.streams:type_name -> frkr.streaming.v1.StreamInfo
	7, // 1: frkr.streaming.v1.StreamInfo.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: frkr.streaming.v1.StreamInfo.updated_at:type_name -> google.protobuf.Timestamp
	7, // 3: frkr.streaming.v1.StreamInfo.deleted_at:type_name -> google.protobuf.Timestamp
	5, // 4: frkr.streaming.v1.StreamMessage.headers:type_name -> frkr.streaming.v1.StreamMessage.HeadersEntry
	6, // 5: frkr.streaming.v1.StreamMessage.query:type_name -> frkr.streaming.v1.StreamMessage.QueryEntry
	0, // 6: frkr.streaming.v1.StreamingService.ListStreams:input_type -> frkr.streaming.v1.ListStreamsRequest
	3, // 7: frkr.streaming.v1.StreamingService.OpenStream:input_type -> frkr.streaming.v1.OpenStreamRequest
	1, // 8: frkr.streaming.v1.StreamingService.ListStreams:output_type -> frkr.streaming.v1.ListStreamsResponse
	4, // 9: frkr.streaming.v1.StreamingService.OpenStream:output_type -> frkr.streaming.v1.StreamMessage
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_streaming_v1_streaming_proto_init() }
func file_streaming_v1_streaming_proto_init() {
	if File_streaming_v1_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_v1_streaming_proto_rawDesc), len(file_streaming_v1_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_v1_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_v1_streaming_proto_depIdxs,
		MessageInfos:      file_streaming_v1_streaming_proto_msgTypes,
	}.Build()
	File_streaming_v1_streaming_proto = out.File
	file_streaming_v1_streaming_proto_goTypes = nil
	file_streaming_v1_streaming_proto_depIdxs = nil
}
