// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ingest/v1/ingest.proto

package ingestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IngestRequest represents a request to ingest a mirrored API request
type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Request       *MirroredRequest       `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_ingest_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_ingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *IngestRequest) GetRequest() *MirroredRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// MirroredRequest represents a mirrored HTTP request
type MirroredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Query         map[string]string      `protobuf:"bytes,5,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampNs   int64                  `protobuf:"varint,6,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirroredRequest) Reset() {
	*x = MirroredRequest{}
	mi := &file_ingest_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirroredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirroredRequest) ProtoMessage() {}

func (x *MirroredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirroredRequest.ProtoReflect.Descriptor instead.
func (*MirroredRequest) Descriptor() ([]byte, []int) {
	return file_ingest_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *MirroredRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MirroredRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MirroredRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *MirroredRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MirroredRequest) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *MirroredRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *MirroredRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// IngestResponse represents the response from the ingest gateway
type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_ingest_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_ingest_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IngestResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_ingest_v1_ingest_proto protoreflect.FileDescriptor

const file_ingest_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x16ingest/v1/ingest.proto\x12\x0efrkr.ingest.v1\"g\n" +
	"\rIngestRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x129\n" +
	"\arequest\x18\x02 \x01(\v2\x1f.frkr.ingest.v1.MirroredRequestR\arequest\"\x93\x03\n" +
	"\x0fMirroredRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12F\n" +
	"\aheaders\x18\x03 \x03(\v2,.frkr.ingest.v1.MirroredRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12@\n" +
	"\x05query\x18\x05 \x03(\v2*.frkr.ingest.v1.MirroredRequest.QueryEntryR\x05query\x12!\n" +
	"\ftimestamp_ns\x18\x06 \x01(\x03R\vtimestampNs\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x0eIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId2X\n" +
	"\rIngestService\x12G\n" +
	"\x06Ingest\x12\x1d.frkr.ingest.v1.IngestRequest\x1a\x1e.frkr.ingest.v1.IngestResponseB5Z3github.com/frkr-io/frkr-proto/go/ingest/v1;ingestv1b\x06proto3"

var (
	file_ingest_v1_ingest_proto_rawDescOnce sync.Once
	file_ingest_v1_ingest_proto_rawDescData []byte
)

func file_ingest_v1_ingest_proto_rawDescGZIP() []byte {
	file_ingest_v1_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_v1_ingest_proto_rawDesc), len(file_ingest_v1_ingest_proto_rawDesc)))
	})
	return file_ingest_v1_ingest_proto_rawDescData
}

var file_ingest_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ingest_v1_ingest_proto_goTypes = []any{
	(*IngestRequest)(nil),   // 0: frkr.ingest.v1.IngestRequest
	(*MirroredRequest)(nil), // 1: frkr.ingest.v1.MirroredRequest
	(*IngestResponse)(nil),  // 2: frkr.ingest.v1.IngestResponse
	nil,                     // 3: frkr.ingest.v1.MirroredRequest.HeadersEntry
	nil,                     // 4: frkr.ingest.v1.MirroredRequest.QueryEntry
}
var file_ingest_v1_ingest_proto_depIdxs = []int32{
	1, // 0: frkr.ingest.v1.IngestRequest.request:type_name -> frkr.ingest.v1.MirroredRequest
	3, // 1: frkr.ingest.v1.MirroredRequest.headers:type_name -> frkr.ingest.v1.MirroredRequest.HeadersEntry
	4, // 2: frkr.ingest.v1.MirroredRequest.query:type_name -> frkr.ingest.v1.MirroredRequest.QueryEntry
	0, // 3: frkr.ingest.v1.IngestService.Ingest:input_type -> frkr.ingest.v1.IngestRequest
	2, // 4: frkr.ingest.v1.IngestService.Ingest:output_type -> frkr.ingest.v1.IngestResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ingest_v1_ingest_proto_init() }
func file_ingest_v1_ingest_proto_init() {
	if File_ingest_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_v1_ingest_proto_rawDesc), len(file_ingest_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_v1_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_v1_ingest_proto_depIdxs,
		MessageInfos:      file_ingest_v1_ingest_proto_msgTypes,
	}.Build()
	File_ingest_v1_ingest_proto = out.File
	file_ingest_v1_ingest_proto_goTypes = nil
	file_ingest_v1_ingest_proto_depIdxs = nil
}
